##
#
# actionæµ‹è¯•
# 
#


name: actionæµ‹è¯•

on:
  repository_dispatch:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/test.yml'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: æ£€æŸ¥é¡¹ç›®åˆ†æ”¯
        uses: actions/checkout@main

      - name: åˆ›å»ºreleaseæ ‡ç­¾
        id: tag
        if: true && !cancelled()
        run: |
          echo "cat $GITHUB_ENV"
          cat $GITHUB_ENV
          ls $GITHUB_WORKSPACE
          echo "::set-output name=release_tag::$(date +"%Y.%m.%d-%H%M")"
          touch release.txt
          echo "[å›ºä»¶æºç ](https://github.com/coolsnowwolf/lede)" >> release.txt
          echo "ç”±è¡·æ„Ÿè°¢æ‰€æœ‰ä¸ºopenwrtæ— ç§å¥‰çŒ®çš„å¤§ä½¬ä»¬" >> release.txt
          echo "ğŸ“¥ å›ºä»¶ä¸‹è½½" >> release.txt
          echo "::set-output name=status::success"
      - name: å‘å¸ƒè‡³release
        uses: softprops/action-gh-release@v1
        if: steps.tag.outputs.status == 'success' && !cancelled()
        with:
          name: ${{ env.FILE_TIME }} ã€Œ openwrt-zte-e8820s ã€
          tag_name: ${{ steps.tag.outputs.release_tag }}
          body_path: release.txt
          files: ${{ env.GITHUB_WORKSPACE }}/*

      - name: åˆ é™¤æ—§çš„Releases
        uses: dev-drprasad/delete-older-releases@v0.2.0
        if:  true && !cancelled()
        with:
          keep_latest: 9
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
